### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by sylafcode** [dantasulisses/WebMobileInputFix#6]
Hello,

I'm testing your solution.
If it's working, would it be possible to use it on our game?

Thank you :)

**Comment by dantasulisses** [comment]
Sure, go for it! Sorry If I cannot give any support anymore (and it has been a long time since any update)

**Comment by sylafcode** [comment]
Thanks :)
For the moment, it seems I've got no issue on Windows or Android (if not fullscreen).

But for iOS it seems the browser keeps refreshing the webpage, so I need to understand why.
If I find out, I'll let you know, there is no obfuscated libs so it should be okay :)
